enyo.depends(
	"css/CustomKinds.css",
	"css/HomeControl.css",
	"source/CustomKinds.js",
	"source/HomeControl.js",
	"source/extensions/HomeTheater.js",
	"source/extensions/MusicPlayer.js",
	"source/extensions/VideoPlayer.js",
	"source/extensions/StatusInfo.js"
);
